services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Behat contexts need to be public services
    App\Tests\UseCase\UserContext:
        public: true

    App\Tests\E2E\UserContext:
        public: true
        arguments:
            $kernel: '@kernel'
            $mongoClient: '@MongoDB\Client'
            $mongoDatabase: '%env(MONGODB_DATABASE)%'
