services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Behat contexts need to be public services
    UseCase\UserContext:
        autowire: true

    E2E\UserContext:
        autowire: true
        arguments:
            $kernel: '@kernel'
