services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Behat contexts need to be public services
    App\Tests\UseCase\UserContext:
        autowire: true

    App\Tests\E2E\UserContext:
        autowire: true
        arguments:
            $kernel: '@kernel'
